[package]
name = "vx-cas-proto"
version.workspace = true
edition.workspace = true

[dependencies]
facet = { workspace = true }
rapace = { workspace = true }
blake3 = { workspace = true }
camino = { workspace = true }
jiff = { workspace = true }
