[package]
name = "vx-report"
version.workspace = true
edition.workspace = true

[dependencies]
facet = { workspace = true }
facet-json = { workspace = true }
camino = { workspace = true }
vx-cas-proto = { workspace = true }
