[package]
name = "vx-report"
version.workspace = true
edition.workspace = true

[dependencies]
facet = { workspace = true }
facet-json = { workspace = true }
camino = { workspace = true }
ulid = "1.2"
vx-cass-proto = { workspace = true }
