[package]
name = "vx-cc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
camino = { workspace = true }
thiserror = { workspace = true }
vx-cas-proto = { path = "../vx-cas-proto" }

[dev-dependencies]
