[package]
name = "vx-execd"
version.workspace = true
edition.workspace = true

[dependencies]
facet = { workspace = true }
rapace = { workspace = true }
tokio = { workspace = true }
camino = { workspace = true }
eyre = { workspace = true }
jiff = { workspace = true }

vx-cas-proto = { workspace = true }
vx-exec-proto = { workspace = true }
