[package]
name = "vx-project"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
facet.workspace = true
facet-kdl.workspace = true
camino.workspace = true
thiserror.workspace = true
