[package]
name = "vx-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
facet = { workspace = true }
picante = { workspace = true }
rapace = { workspace = true }
tokio = { workspace = true }
blake3 = { workspace = true }
camino = { workspace = true }
eyre = { workspace = true }

vx-cas-proto = { workspace = true }
vx-exec-proto = { workspace = true }
vx-daemon-proto = { workspace = true }
vx-manifest = { workspace = true }
vx-casd = { workspace = true }
vx-execd = { workspace = true }
